### ISSUE TITLE
Censorship prevents links from working as expected

### ISSUE THREAD

**Issue by mboevink** [4577/loult-ng#107]
Any link containing a censored word does not work as expected. You're preventing some VERY high quality messages from being sent.

A common example: http://www.sexy-parade.com/video/la-bite-hors-norme-du-black-dechire-la-petite-asiatique-sexy-4389.html

**Comment by ghost** [comment]
Not an ideal fix as the whole message is unfiltered if it contains a link, but at least the links will work correctly now.
¯\\_(ツ)_/¯
