### ISSUE TITLE
trim attack messages

### ISSUE THREAD

**Issue by ghost** [4577/loult-ng#23]
Sending "/attack bulbizarre " with a trailing whitespace crashes the client and forces the attacker to refresh in order to speak again

msg = msg.strip()

^should do the trick
Probably a good idea to have that outside of the attacks, for regular messages too.

**Comment by hadware** [comment]
le

**Comment by ghost** [comment]
okéw

**Comment by ghost** [comment]
Note: all messages are now also trimmed client side before being sent because reasons
Note: trim server side anyway (alternative clients are real)
