### ISSUE TITLE
Centering issues on all versions of lou - IE

### ISSUE THREAD

**Issue by mboevink** [4577/loult-ng#36]
Tested under IE 11.0.9600.18538 and ie 10 

Appreciate some help with this - certainly not an expert in flex
![capture](https://cloud.githubusercontent.com/assets/3157750/23794297/8ea10e22-05e3-11e7-9419-27663ec1ec01.PNG)

**Comment by ghost** [comment]
I will get to it, but I'm not home for another week or so.
Glad to see you are back!

**Comment by ghost** [comment]
So, the div needed a fixed width to be centered in IE. Should be ok next reboot!

See https://github.com/4577/loult-ng/commit/870f05d4c49f62c9b10cf5cc29522c52a0048d65
