### ISSUE TITLE
Button padding issues on mobile

### ISSUE THREAD

**Issue by mboevink** [4577/loult-ng#53]
See attached. 

Also after a bit of spam the connection drops without fail. Australian internet however...
![img_0496](https://cloud.githubusercontent.com/assets/3157750/25314668/c2b64c7a-288b-11e7-9fdc-fad57eb73da3.PNG)

**Comment by mboevink** [comment]
Edit: appears to be in all webkit browsers. Tested from Safari 10.1

**Comment by ghost** [comment]
I would like to have utf8 symbols instead of the images in the next update, hopefully it will fix that too!
Thanks

**Comment by ghost** [comment]
Should be fixed now?

**Comment by mboevink** [comment]
Same problem on both safari desktop and mobile.

**Comment by mboevink** [comment]
Fixed as of 18 / 05
