### ISSUE TITLE
Cannot connect to loult.family via proxy

### ISSUE THREAD

**Issue by mboevink** [4577/loult-ng#6]
> WebSocket connection to 'ws://loult.family/socket/' failed: Establishing a tunnel via proxy server failed.

Yet lou.lt works like a charm (But had the same issue originally).

Proxy SQUID
Browser tested: All

*_Edit: *_ Looks like the update to WSS fixes it as proxies can't tamper with encrypted data.

**Comment by 4577** [comment]
A letsencryt cert has been deployed on the server (configuration was based off [Mozilla's generator](https://mozilla.github.io/server-side-tls/ssl-config-generator/) with modern settings, as the [compatibility matrix](http://caniuse.com/#feat=audio-api) for the audio API we use includes its browser support).

I didn't enable forced HTTPS redirection (HSTS) yet, are we sure this would have zero noticeable impact on the clients performance-wise?

**Comment by mboevink** [comment]
![capture](https://cloud.githubusercontent.com/assets/3157750/15854860/79502cba-2cef-11e6-9441-042a193fb4c6.jpg)

First: I can confirm that it is working as expected through a SQUID proxy.
Two: Loult and millions of other websockets sites are running https. It'll be fine.

**Comment by 4577** [comment]
HSTS and HTTPS redirection were applied.
