### ISSUE TITLE
Fix and investigate added latency when connecting to websocket

### ISSUE THREAD

**Issue by 4577** [4577/loult-ng#7]
When loading the page for the first time on some time lapse (?), latency can be observed between loading the page and the display of lines in the chat window.

See if this is related to the switch to HTTPS, the broadcast of connection message or another factor.

**Comment by mboevink** [comment]
Don't do it man, some of us need to connect from work. Alternatively just remove your 301 / HSTS so its optional.

**Comment by 4577** [comment]
I know. In all cases I'm not going to disable HTTPS, which should not be intrinsic cause of this.

**Comment by 4577** [comment]
Current server-side optimizations seem to have been satisfying enough. (HTTP/2 is now used for serving static content, among other tweaks.)
